---
title: "05-class-ds4ir-assignment"
author: "seu nome aqui"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output: 
  html_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(geobr)
library(ggplot2)
library(sf)
library(dplyr)
library(rio)


```

# Assignment {-}

Você deve reproduzir os três mapas apresentados na vinheta do pacote [`geobr`](https://cran.r-project.org/web/packages/geobr/vignettes/intro_to_geobr.html). Have fun!

```{r echo=FALSE, warning=FALSE, message=FALSE}
meso <- read_intermediate_region(year=2017)
states <- read_state(year=2014)

# Remove plot axis
no_axis <- theme(axis.title=element_blank(),
                   axis.text=element_blank(),
                   axis.ticks=element_blank())


```

```{r echo=FALSE, warning=FALSE, message=FALSE}
# Plot all Brazilian states
  ggplot() +
    geom_sf(data=states, fill="#2D3E50", color="#FEBF57", size=.15, show.legend = FALSE) +
    labs(subtitle="States", size=8) +
    theme_minimal() +
    no_axis
```


```{r echo=FALSE, warning=FALSE, message=FALSE}
# Download all municipalities of Rio
all_muni <- read_municipality( code_muni = "RJ", year= 2000)

# plot
ggplot() +
    geom_sf(data=all_muni, fill="#2D3E50", color="#FEBF57", size=.15, show.legend = FALSE) +
    labs(subtitle="Municipalities of Rio de Janeiro, 2000", size=8) +
    theme_minimal() +
    no_axis


```


```{r echo=FALSE, warning=FALSE, message=FALSE}
# download Life Expectancy data
adh <- rio::import("http://atlasbrasil.org.br/2013/data/rawData/Indicadores%20Atlas%20-%20RADAR%20IDHM.xlsx", which = "Dados")

# keep only information for the year 2010 and the columns we want
adh <- subset(adh, ANO == 2014)

# Download the sf of all Brazilian states
states <- read_state(year= 2014)

# joind the databases
states <-left_join(states, adh, by = c("abbrev_state" = "NOME_AGREGA"))
  
ggplot() +
    geom_sf(data=states, aes(fill=ESPVIDA), color= NA, size=.15) +
      labs(subtitle="Life Expectancy at birth, Brazilian States, 2014", size=8) +
      scale_fill_distiller(palette = "Blues", name="Life Expectancy", limits = c(65,80)) +
      theme_minimal() +
      no_axis  
```

# Produza um documento .html com o resultado de sua análise

**Observação**: Não se esqueça de colocar seu nome.



